shop/urls.py
from django.urls import path
from shop import views

app_name = "shop"
urlpatterns = [
    path("", views.shop_home, name="shop_home"),
    path("store/products/", views.product_list, name="product_list"),
    path("store/orders/", views.order_list, name="order_list"),
    path("store/products/add/", views.new_product, name="new_product"),
    path("products/<uuid:pk>/", views.product_detail, name="product_detail"),
    path("store/products/<uuid:pk>/", views.merchant_product_detail, name="merchant_product_detail"),
    path("store/products/<uuid:pk>/edit/", views.edit_product, name="edit_product"),
    path("cart/", views.cart_detail, name="cart_detail"),
    path("cart/<uuid:pk>/add/", views.cart_add, name="cart_add"),
    path("cart/<uuid:pk>/remove/", views.cart_remove, name="cart_remove"),
    path("cart/checkout/", views.cart_checkout, name="checkout"),
    path("store/add/", views.new_store, name="new_store"),
    path("store/edit/", views.edit_store, name="edit_store"),
]

shop/models.py
import os
import uuid
from django.db import models
from django.contrib.auth.models import User
from common.models import BaseModel
from addresses.models import Address
from accounts.models import Profile
from companies.models import Employee

# Create your models here.


def store_logos(instance, filename):
    file_ext = os.path.splitext(filename)[1]
    return "logos/stores/store_{0}{1}".format(instance.id, file_ext)


class Store(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    logo = models.ImageField(upload_to=store_logos,null=True,blank=True)
    name = models.CharField(max_length=255)
    address = models.ForeignKey(
        Address, on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField()
    rating = models.DecimalField(default=0, decimal_places=1, max_digits=2)
    verified = models.BooleanField(default=False)


class Merchant(BaseModel, Profile):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    store = models.ForeignKey(
        Store, on_delete=models.CASCADE, null=True, blank=True)


class Album(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(null=True, blank=True, max_length=100)


def get_upload_directory(instance, filename):
    file_ext = os.path.splitext(filename)[1]
    return "album_{0}/pic_{1}{2}".format(instance.album.id, instance.id, file_ext)


class Picture(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    attachment = models.ImageField(upload_to=get_upload_directory)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)


class Category(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    is_parent = models.BooleanField(default=True)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    parent_category = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True)
    slug = models.SlugField(default="others")

    class Meta:
        verbose_name_plural = "categories"


def cover_image_location(instance, filename):
    file_ext = os.path.splitext(filename)[1]
    return "covers/store_{0}/product_{1}{2}".format(instance.store.id, instance.id, file_ext)


class Product(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    description = models.TextField()
    old_price = models.DecimalField(max_digits=10, decimal_places=2)
    new_price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity_in_stock = models.IntegerField()
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    cover_image = models.ImageField(upload_to=cover_image_location,null=True,blank=True)
    album = models.OneToOneField(
        Album, on_delete=models.CASCADE, null=True, blank=True)


class Order(BaseModel):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through="OrderItem")
    total_amount = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True)
    STATUS_CHOICES = (
        ("pending", "Pending"),
        ("on_hold", "On Hold"),
        ("processing", "Processing"),
        ("in_transit", "In Transit"),
        ("delivered", "Delivered")
    )
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="pending")


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    price = models.DecimalField(max_digits=10, decimal_places=2)

shop/forms.py
from django import forms
from shop.models import Product, Order, Store, Category


class ProductForm(forms.ModelForm):
    pictures = forms.FileField(
        required=False, widget=forms.ClearableFileInput(attrs={"multiple": True}))

    class Meta:
        model = Product
        fields = ("name", "cover_image","pictures", "description", "old_price",
                  "new_price", "quantity_in_stock", "category")
    def __init__(self,is_parent,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields["category"].queryset = Category.objects.filter(is_parent=True)


CART_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartItemAddForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=CART_QUANTITY_CHOICES, coerce=int)
    update_quantity = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)


class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = ("name", "description")

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Store, Merchant, Product, Category, Album, Picture, Order, OrderItem
from shop.forms import ProductForm, CartItemAddForm, StoreForm
from addresses.forms import AddressForm
from shop.shopping import Cart

# Create your views here.


def product_list(request):
    store = request.user.merchant.store
    queryset = Product.objects.filter(store=store)
    return render(request, "shop/product_list.html", {"products": queryset})


def order_list(request):
    store = request.user.merchant.store
    queryset = OrderItem.objects.filter(store=store)
    return render(request, "shops/order_list.html", {"orders": queryset})


def new_product(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            album = Album.objects.create()
            for file in request.FILES.getlist("pictures"):
                Picture.objects.create(attachment=file, album=album)
            product.created_by = request.user
            product.store = request.user.merchant.store
            product.album = album
            product.save()
            return redirect("shop:merchant_product_detail", pk=product.pk)
    else:
        form = ProductForm()
    return render(request, "shop/new_product.html", {"form": form})


def edit_product(request, pk):
    if request.method == "POST":
        store = request.user.merchant.store
        obj = get_object_or_404(Product.objects.filter(store=store), pk=pk)
        form = ProductForm(request.POST, instance=obj)
        if form.is_valid():
            product = form.save(commit=False)
            product.edited_by = request.user
            product.save()
            return redirect(request, "shop:merchant_product_detail", pk=product.pk)
    else:
        form = ProductForm()
    return render(request, "shop/new_product.html", {"form": form})


def new_store(request):
    if request.method == "POST":
        form = StoreForm(request.POST, request.FILES, prefix="sto")
        addr = AddressForm(request.POST, prefix="addr")
        if form.is_valid() and addr.is_valid():
            store = form.save(commit=False)
            address = addr.save(commit=False)
            address.created_by = request.user
            address.save()
            store.address = address
            store.created_by = request.user
            store.save()
            merch = request.user.merchant
            merch.store = store
            merch.save()
            return redirect("shop:product_list")
    else:
        form = StoreForm(prefix="sto")
        addr = AddressForm(prefix="addr")
    return render(request, "shop/new_store.html", {"form": form, "addr": addr})


def edit_store(request):
    obj = request.user.merchant.store
    if request.method == "POST":
        form = StoreForm(request.POST, request.FILES,
                         prefix="sto", instance=obj)
        addr = AddressForm(request.POST, prefix="addr", instance=obj.address)
        if form.is_valid() and addr.is_valid():
            store = form.save(commit=False)
            address = addr.save(commit=False)
            address.edited_by = request.user
            store.edited_by = request.user
            address.save()
            store.save()
            return redirect("shop:product_list")
    else:
        form = StoreForm(prefix="sto", instance=obj)
        addr = AddressForm(prefix="addr", instance=obj.address)
    return render(request, "shop/new_store.html", {"form": form, "addr": addr})


def product_detail(request, pk):
    product = get_object_or_404(Product.objects.filter(active=True), pk=pk)
    form = CartItemAddForm()
    return render(request, "shop/product_detail.html", {"product": product, "form": form})

def merchant_product_detail(request,pk):
    store = request.user.merchant.store
    product = get_object_or_404(Product.objects.filter(store=store),pk=pk)
    return render(request,"shop/product_detail.html",{"product":product})

def shop_home(request):
    queryset = Product.objects.filter(active=True)
    return render(request, "shop/shop_home.html", {"products": queryset})


@require_POST
def cart_add(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=pk)
    form = CartItemAddForm(request.POST)
    if form.is_valid():
        clean_d = form.cleaned_data
        cart.add_item(
            product=product,
            quantity=clean_d["quantity"],
            update_quantity=clean_d["update"])
        return redirect("shop:cart_detail")


def cart_remove(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=pk)
    cart.remove_item(product)
    return redirect("shop:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["item_update_form"] = CartItemAddForm(
            initial={"quantity": item["quantity"], "update": True})
    return render(request, "shop/cart_detail.html", {"cart": cart})


def cart_checkout(request):
    cart = Cart(request)
    if request.method == "POST":
        if len(cart) > 0:
            order = Order(employee=request.user)
            cost_count = 0
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    quantity=item["quantity"],
                    unit_price=item["price"],
                    price=item["total_price"],
                    store=item["product"].store)
                cost_count += item["total_price"]
            order.total_amount = cost_count
            order.save()
            cart.clear_items()
            return render(request, "shop/order_sent.html", {"order": order})
        else:
            return redirect("shop:shop_home")
    else:
        return render(request, "shop/checkout.html", {"cart": cart})

shop/templates/shop/cart_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}My Cart{% endblock %} 
{% block content %}
<div id="cart-detail" class="clearfix">
    <div class="col-md-12">
        <div class="order-summary clearfix">
            <div class="section-title">
                <h3 class="title">My Cart</h3>
            </div>
            <table class="shopping-cart-table table">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th></th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Quantity</th>
                        <th class="text-center">Total</th>
                        <th class="text-right"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="thumb">
                            <img src="{% static 'img/thumb-product01.jpg' %}" alt="">
                        </td>
                        <td class="details">
                            <a href="#">Product Name Goes Here</a>
                            <ul>
                                <li>
                                    <span>Size: XL</span>
                                </li>
                                <li>
                                    <span>Color: Camelot</span>
                                </li>
                            </ul>
                        </td>
                        <td class="price text-center">
                            <strong>$32.50</strong>
                            <br>
                            <del class="font-weak">
                                <small>$40.00</small>
                            </del>
                        </td>
                        <td class="qty text-center">
                            <input class="input" type="number" value="1">
                        </td>
                        <td class="total text-center">
                            <strong class="primary-color">$32.50</strong>
                        </td>
                        <td class="text-right">
                            <button class="main-btn icon-btn">
                                <i class="fa fa-close"></i>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td class="thumb">
                            <img src="{% static 'img/thumb-product01.jpg' %}" alt="">
                        </td>
                        <td class="details">
                            <a href="#">Product Name Goes Here</a>
                            <ul>
                                <li>
                                    <span>Size: XL</span>
                                </li>
                                <li>
                                    <span>Color: Camelot</span>
                                </li>
                            </ul>
                        </td>
                        <td class="price text-center">
                            <strong>$32.50</strong>
                        </td>
                        <td class="qty text-center">
                            <input class="input" type="number" value="1">
                        </td>
                        <td class="total text-center">
                            <strong class="primary-color">$32.50</strong>
                        </td>
                        <td class="text-right">
                            <button class="main-btn icon-btn">
                                <i class="fa fa-close"></i>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td class="thumb">
                            <img src="{% static 'img/thumb-product01.jpg' %}" alt="">
                        </td>
                        <td class="details">
                            <a href="#">Product Name Goes Here</a>
                            <ul>
                                <li>
                                    <span>Size: XL</span>
                                </li>
                                <li>
                                    <span>Color: Camelot</span>
                                </li>
                            </ul>
                        </td>
                        <td class="price text-center">
                            <strong>$32.50</strong>
                        </td>
                        <td class="qty text-center">
                            <input class="input" type="number" value="1">
                        </td>
                        <td class="total text-center">
                            <strong class="primary-color">$32.50</strong>
                        </td>
                        <td class="text-right">
                            <button class="main-btn icon-btn">
                                <i class="fa fa-close"></i>
                            </button>
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>TOTAL</th>
                        <th colspan="2" class="total">$97.50</th>
                    </tr>
                </tfoot>
            </table>
            <div class="pull-right">
                <a href="{% url 'shop:checkout' %}">
                    <button class="primary-btn">Checkout</button>
                </a>
            </div>
        </div>

    </div>
</div>
{% endblock %}

shop/templates/shop/checkout.html
{% extends "base.html" %}{% block title %}Checkout{% endblock %} {% block content %}
<form id="checkout-form" class="clearfix" method="POST">
	<div class="col-md-12">
		<div class="order-summary clearfix">
			<div class="section-title">
				<h3 class="title">Order Review</h3>
			</div>
			<table class="shopping-cart-table table">
				<thead>
					<tr>
						<th>Product</th>
						<th></th>
						<th class="text-center">Price</th>
						<th class="text-center">Quantity</th>
						<th class="text-center">Total</th>
						<th class="text-right"></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td class="thumb">
							<img src="./img/thumb-product01.jpg" alt="">
						</td>
						<td class="details">
							<a href="#">Product Name Goes Here</a>
							<ul>
								<li>
									<span>Size: XL</span>
								</li>
								<li>
									<span>Color: Camelot</span>
								</li>
							</ul>
						</td>
						<td class="price text-center">
							<strong>$32.50</strong>
							<br>
							<del class="font-weak">
								<small>$40.00</small>
							</del>
						</td>
						<td class="qty text-center">
							<input class="input" type="number" value="1">
						</td>
						<td class="total text-center">
							<strong class="primary-color">$32.50</strong>
						</td>
						<td class="text-right">
							<button class="main-btn icon-btn">
								<i class="fa fa-close"></i>
							</button>
						</td>
					</tr>
					<tr>
						<td class="thumb">
							<img src="./img/thumb-product01.jpg" alt="">
						</td>
						<td class="details">
							<a href="#">Product Name Goes Here</a>
							<ul>
								<li>
									<span>Size: XL</span>
								</li>
								<li>
									<span>Color: Camelot</span>
								</li>
							</ul>
						</td>
						<td class="price text-center">
							<strong>$32.50</strong>
						</td>
						<td class="qty text-center">
							<input class="input" type="number" value="1">
						</td>
						<td class="total text-center">
							<strong class="primary-color">$32.50</strong>
						</td>
						<td class="text-right">
							<button class="main-btn icon-btn">
								<i class="fa fa-close"></i>
							</button>
						</td>
					</tr>
					<tr>
						<td class="thumb">
							<img src="./img/thumb-product01.jpg" alt="">
						</td>
						<td class="details">
							<a href="#">Product Name Goes Here</a>
							<ul>
								<li>
									<span>Size: XL</span>
								</li>
								<li>
									<span>Color: Camelot</span>
								</li>
							</ul>
						</td>
						<td class="price text-center">
							<strong>$32.50</strong>
						</td>
						<td class="qty text-center">
							<input class="input" type="number" value="1">
						</td>
						<td class="total text-center">
							<strong class="primary-color">$32.50</strong>
						</td>
						<td class="text-right">
							<button class="main-btn icon-btn">
								<i class="fa fa-close"></i>
							</button>
						</td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<th class="empty" colspan="3"></th>
						<th>SUBTOTAL</th>
						<th colspan="2" class="sub-total">$97.50</th>
					</tr>
					<tr>
						<th class="empty" colspan="3"></th>
						<th>SHIPING</th>
						<td colspan="2">Free Shipping</td>
					</tr>
					<tr>
						<th class="empty" colspan="3"></th>
						<th>TOTAL</th>
						<th colspan="2" class="total">$97.50</th>
					</tr>
				</tfoot>
			</table>
			<div class="pull-right">
				<button class="primary-btn">Place Order</button>
			</div>
		</div>

	</div>
</form>
{% endblock %}

shop/templates/shop/new_product.html
{% extends "base.html" %} 
{% load widget_tweaks %} 
{% block title %}New Product{% endblock %} 
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% include "form.html" %}
    {% for hidden in addr.hidden_fields %} {{ hidden }} {% endfor %} 
    {% for field in addr.visible_fields %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }} 
        {% for error in field.errors %}
        <span class="help-block">
            {{ error }}
        </span>
        {% endfor %}
    </div>
    {% endfor %}
    <div class="fph ac">
        <button type="submit" class="pdlr10p pdtb10 rc20 m0a">Submit</button>
    </div>
</form>
{% endblock %}

shop/templates/shop/new_store.html
{% extends "base.html" %} 
{% load widget_tweaks %} 
{% block title %}New Store{% endblock %} 
{% block content %}
<form method="POST">
    {% include "form.html" %}
    {% for hidden in addr.hidden_fields %} {{ hidden }} {% endfor %} 
    {% for field in addr.visible_fields %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }} 
        {% for error in field.errors %}
        <span class="help-block">
            {{ error }}
        </span>
        {% endfor %}
    </div>
    {% endfor %}
    <div class="fph ac">
        <button type="submit" class="pdlr10p pdtb10 rc20 m0a">Submit</button>
    </div>
</form>
{% endblock %}